@clientid = 08be0586-95b1-48d6-abf5-cf1d31d00569
@clientsecret = dW18Q~n51wrmvbZBzlHjpmJgkzgo8k0YavG3KbtO
@scope = https://api.businesscentral.dynamics.com/.default
@tenant = 986f6f78-397c-41a1-8ad0-3e3352ac50a1

# @name tokenrequest
POST https://login.microsoftonline.com/{{tenant}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{clientid}}
&client_secret={{clientsecret}}
&scope={{scope}}
###
@token = {{tokenrequest.response.body.access_token}}
###
@baseurl = https://api.businesscentral.dynamics.com/v2.0/DevEnvironment

# @name companies
GET  {{baseurl}}/api/v2.0/companies
Authorization: Bearer {{token}}

# for get Items
###
GET  {{baseurl}}/api/v2.0/companies(8dd5bced-fe94-ef11-8a6d-6045bdc8adeb)/items
Authorization: Bearer {{token}}